display: Fix declaration type of a GCompareDataFunc
`GCompareDataFunc` takes a `user_data` parameter, which C strictly
doesn’t like you casting away, because it *will* cause problems on
architectures where the callee pops arguments off the stack.

Fixes warning:
```
../panels/display/cc-display-settings.c: In function ‘cc_display_settings_rebuild_ui’:
../panels/display/cc-display-settings.c:518:45: error: cast between incompatible function types from ‘gint (*)(CcDisplayMode *, CcDisplayMode *)’ {aka ‘int (*)(struct _CcDisplayMode *, struct _CcDisplayMode *)’} to ‘gint (*)(const void *, const void *, void *)’ {aka ‘int (*)(const void *, const void *, void *)’} [-Werror=cast-function-type]
  518 |                                             (GCompareDataFunc) sort_modes_by_refresh_rate_desc,
```

Signed-off-by: Philip Withnall <pwithnall@gnome.org>