flatpak: bump NetworkManager to version 1.14.0
The build option `-ltinfo` is required, otherwise a few errors related
to libreadline.so will be thrown like:

libreadline.so: undefined reference to `tputs'
libreadline.so: undefined reference to `tgoto'
libreadline.so: undefined reference to `tgetflag'