ci: Install dnf5-plugins instead of dnf-plugins-core
Since "builddep" is part of dnf5-plugins in DNF5.

See https://gitlab.gnome.org/GNOME/gnome-control-center/-/jobs/2933787

Unknown argument "builddep" for command "dnf5". Add "--help" for more information about the arguments.
$ echo "== Installing =="
== Installing ==
$ ninja -C _build install
ninja: Entering directory `_build'
ninja: fatal: chdir to '_build' - No such file or directory
Cleaning up project directory and file based variables 00:02
ERROR: Job failed: exit code 1